[package]
name = "handler"
version = "0.1.0"
authors = ["Danilo Pereira <dnp1@users.noreply.github.com>"]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
request = {path = "../request"}
iron = "^0.6"